---
name: Test Learn GitHub
description: Internal action of Learn GitHub in Y minutes
branding:
  color: blue
  icon: terminal
inputs:
  cache:
    required: false
    description: If caching should be used
    default: true
  key-prefix:
    required: false
    description: Add prefix to cache key (for refresh or identification)
  location:
    required: false
    description: Where to install Learn GitHub
    default: >-
      ${{ case(runner.os == 'Windows', 'C:\LearnGitHub', '/opt/LearnGitHub') }}
  verbose:
    required: false
    description: Show version and location
    default: false
  version:
    required: false
    description: A specific version to install
    default: 0.1.1
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: macOS need `sudo` to create
      if: steps._.outputs.cache-hit != 'true' && runner.os == 'macOS'
      shell: bash
      run: |
        sudo mkdir -p "${{ inputs.location }}"
        sudo chown runner:staff "${{ inputs.location }}"

    - name: Restore cached Learn GitHub directory
      id: _
      if: fromJSON(inputs.cache)
      uses: actions/cache/restore@v5
      with:
        key: ${{ format('{0}_Learn_GitHub_{1}_{2}',
          inputs.key-prefix, inputs.version, runner.os) }}
        path: ${{ inputs.location }}

    - name: Install Learn GitHub
      if: steps._.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p "${{ inputs.location }}"
        cp -r dists/* "${{ inputs.location }}"

    - name: Save cached Learn GitHub directory
      if: steps._.outputs.cache-hit != 'true' && fromJSON(inputs.cache)
      uses: actions/cache/save@v5
      with:
        key: ${{ format('{0}_Learn_GitHub_{1}_{2}',
          inputs.key-prefix, inputs.version, runner.os) }}
        path: ${{ inputs.location }}

    - name: Learn GitHub environments variables
      shell: bash
      run: |
        ptrn="^(path|learn_github)="
        pd="${{ case(runner.os == 'Windows', ';', ':') }}"
        if ${{ runner.os == 'Windows' }} ; then
          MSYS2_ARG_CONV_EXCL='*' MSYS2_ENV_CONV_EXCL='*' \
            cmd /d /c "${{ inputs.location }}\setvars.bat && python env.py -0"
        else
          . "${{ inputs.location }}/setvars.sh"
          env -0
        fi | grep -E -i -z "$ptrn" | tr '\0' '\n' > /tmp/envs
        grep -v -i "^path=" /tmp/envs >> $GITHUB_ENV
        sed -n "/^path=\([^${pd}]*\)${pd}.*$/Is//\\1/p" /tmp/envs \
          | sed '1!G;h;$!d' >> $GITHUB_PATH

        if ${{ fromJSON(inputs.verbose) }} ; then
          echo GITHUB_ENV=$GITHUB_ENV
          cat $GITHUB_ENV
          echo GITHUB_PATH=$GITHUB_PATH
          cat $GITHUB_PATH
        fi

    - name: Show version for Unix
      if: fromJSON(inputs.verbose) && runner.os != 'Windows'
      shell: bash
      run: |
        echo "PATH=$PATH"
        echo "---"
        echo "LEARN_GITHUB=$LEARN_GITHUB"
        type learn_github
        learn_github

    - name: Show version Windows
      if: fromJSON(inputs.verbose) && runner.os == 'Windows'
      shell: cmd
      run: |
        echo "PATH=%PATH%"
        echo "---"
        echo "LEARN_GITHUB=%LEARN_GITHUB%"
        rem TODO ?? where learn_github
        learn_github
