---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

name: Рабочий процесс изучения GitHub за Y минут

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # https://github.com/adambard/learnxinyminutes-docs/blob/master/ru/yaml.md

  # Комментарий в YAML выглядит как-то так.
  # YAML supports single-line comments.

  ######################
  # Скалярные величины #
  ######################

  # Наш корневой объект (который продолжается до конца документа) будет
  # соответствовать типу map, который в свою очередь соответствует словарю,
  # хешу или объекту в других языках.

  key: value
  another_key: Другое значение ключа.
  a_number_value: 100
  scientific_notation: 1e+12
  hex_notation: 0x123   # evaluates to 291
  # ПРЕДУПРЕЖДЕНИЕ: GitHub не поддерживает восьмеричные целые
  octal_notation: 0123  # evaluates to 83
  # Число 1 будет интерпретировано как число, а не как логический тип. Если
  # необходимо чтобы значение было интерпретировано как логическое, необходимо
  # использовать true
  boolean: true
  null_value: null
  another_null_value: ~  # TODO ru
  key with spaces: value

  # Yes and No (doesn't matter the case) will be evaluated to boolean
  # true and false values respectively.
  # To use the actual value use single or double quotes.
  # yamllint disable-line rule:truthy
  no: no            # evaluates to "no": false
  # yamllint disable-line rule:truthy
  yes: No           # evaluates to "yes": false
  # yamllint disable-line rule:truthy
  not_enclosed: yes  # evaluates to "not_enclosed": true
  enclosed: "yes"    # evaluates to "enclosed": yes
  # ПРЕДУПРЕЖДЕНИЕ: GitHub не распознаёт no/yes как boolean
  # TODO: возможно это устаревшая версия YAML

  # Обратите внимание что строки используются без кавычек, но могут и с
  # кавычками.
  however: 'Строка заключенная в кавычки.'
  # ПРЕДУПРЕЖДЕНИЕ: `PowerShell` и `bash` требуют особенного способа доступа к
  #                 `Ключ заключенный в кавычки.`, `single quotes`
  'Ключ заключенный в кавычки.': "Полезно если нужно использовать ':' в вашем
    ключе."
  single quotes: 'Содержит ''одну'' экранированную строку'
  # ПРЕДУПРЕЖДЕНИЕ: GitHub корректно распознаёт и устанавливает
  #                 `env.double quotes`.  Однако, переменные окружения
  #                 обрезаются по символу `\0`.
  double quotes: "Содержит несколько: \", \0, \t, \u263A, \x0d\x0a == \r\n,
    экранированных строк."

  # UTF-8/16/32 characters need to be encoded
  # ПРЕДУПРЕЖДЕНИЕ: GitHub не распознаёт и не декодирует esc-последовательности
  Superscript two: \u00B2
  Superscript two quote: "\u00B2"
  Superscript two UTF-8: ²

  # Special characters must be enclosed in single or double quotes
  special_characters: "[ John ] & { Jane } - <Doe>"

  # Многострочные строковые значения могут быть записаны как 'строковый блок'
  # (используя |), или как 'сложенный блок' (используя '>').
  # Multiple-line strings can be written either as a 'literal block' (using |),
  # or a 'folded block' (using '>').  Literal block turn every newline within
  # the string into a literal newline (\n).  Folded block removes newlines
  # within the string.
  # ПРЕДУПРЕЖДЕНИЕ: `printenv` неприменим, следует использовать:
  #                 - `env -0` (вариант `printenv -0` linux);
  #                 - запись в `GITHUB_ENV` тоже непроста.
  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#multiline-strings
  literal_block: |
    Значение всего текста в этом блоке будет присвоено ключу 'literal_block',
    с сохранением переноса строк.

    Объявление продолжается до удаления отступа и выравнивания с ведущим
    отступом.

        Любые строки с большим отступом сохраняют остатки своего отступа -
        эта строка будет содержать дополнительно 4 пробела.
  folded_style: >
      Весь блок этого текста будет значением 'folded_style', но в данном случае
      все символы новой строки будут заменены пробелами.

      Пустые строки будут преобразованы в перенос строки.

          Строки с дополнительными отступами сохраняют их переносы строк -
          этот текст появится через 2 строки.

  # |- and >- removes the trailing blank lines (also called literal/block
  # "strip")
  literal_strip: |-
    This entire block of text will be the value of the 'literal_strip' key,
    with trailing blank line being stripped.
  block_strip: >-
    This entire block of text will be the value of 'block_strip', but this
    time, all newlines will be replaced with a single space and
    trailing blank line being stripped.

  # |+ and >+ keeps trailing blank lines (also called literal/block "keep")
  literal_keep: |+
    This entire block of text will be the value of the 'literal_keep' key,
    with trailing blank line being kept.

  block_keep: >+
    This entire block of text will be the value of 'block_keep', but this
    time, all newlines will be replaced with a single space and
    trailing blank line being kept.

  ##################
  # Типы коллекций #
  ##################

  # Контекст GitHub `env` не допускает вложенных словарей, но они есть ниже:
  # `jobs` и т.д.

  # # Вложения используют отступы. Отступ в 2 пробела предпочтителен (но не
  # # обязателен).
  # a_nested_map:
  #   key: value
  #   another_key: Another Value
  #   another_nested_map:
  #     hello: hello

  # В словарях (maps) используются не только строковые значения ключей.
  0.25: a float key

  # Увы, GitHub не поддерживает словари со сложными ключами.

  # # Ключи также могут быть сложными, например многострочными.
  # # Мы используем ? с последующим пробелом, чтобы обозначить начало сложного
  # # ключа.
  # ? |
  # Этот ключ
  # который содержит несколько строк
  # и это его значение
  #
  # # YAML также разрешает соответствия между последовательностями со сложными
  # # ключами
  # # Некоторые парсеры могут выдать предупреждения или ошибку
  # # Пример
  # ? - Manchester United
  #   - Real Madrid
  # : [2001-01-01, 2002-02-02]

  # (Line: 148, Col: 5): A sequence was not expected
  # # Последовательности (эквивалент списка или массива) выглядят как-то так
  # # (обратите внимание что знак '-' считается отступом):
  # a_sequence:
  #   - Item 1
  #   - Item 2
  #   - 0.5  # последовательности могут содержать различные типы.
  #   - Item 4
  #   - key: value
  #     another_key: another_value
  #   -
  #     - Это последовательность
  #     - внутри другой последовательности
  #   - - - Объявления вложенных последовательностей
  #       - могут быть сжаты

  # (Line: 161, Col: 13): A mapping was not expected,
  # # Поскольку YAML это надмножество JSON, вы можете использовать JSON-подобный
  # # синтаксис для словарей и последовательностей:
  # json_map: {"key": "value"}
  # # (Line: 162, Col: 13): A sequence was not expected
  # json_seq: [3, 2, 1, "takeoff"]
  # # (Line: 163, Col: 28): A mapping was not expected
  # в данном случае кавычки не обязательны: {key: [3, 2, 1, takeoff]}

  ##########################
  # Дополнительные функции #
  ##########################

  # ПРЕДУПРЕЖДЕНИЕ: GitHub не везде принимает якоря, в рабочих процессах
  #                 принимает, в `action.yml` - нет.
  # https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#yaml-anchors-and-aliases

  # Anchors identified by & character which define the value.
  # Aliases identified by * character which acts as "see above" command.
  # В YAML есть удобная система так называемых 'якорей' (anchors), которые
  # позволяют легко дублировать содержимое внутри документа. Оба ключа в
  # примере будут иметь одинаковые значения:
  anchored_content: &anchor_name Эта строка будет являться значением обоих
    ключей.
  other_anchor: *anchor_name

  # Anchors are not currently supported. Remove the anchor '...'
  # (Line: 185, Col: 9): A mapping was not expected
  # # Якоря могут использоваться для дублирования/наследования свойств
  # base: &base
  #   name: Каждый будет иметь одинаковое имя

  # # Регулярное выражение << называется ключом объединения независимо от типа
  # # языка.  Он используется, чтобы показать что все ключи одного или более
  # # словарей должны быть добавлены в текущий словарь.
  # # The expression << is called 'Merge Key Language-Independent Type'. It is
  # # used to indicate that all the keys of one or more specified maps should be
  # # inserted into the current map.
  # # NOTE: If key already exists alias will not be merged
  # foo:
  #   # (Line: 193, Col: 5): A mapping was not expected
  #   <<: *base  # doesn't merge the anchor
  #   age: 10
  #   name: John
  # bar:
  #   # (Line: 197, Col: 5): A mapping was not expected
  #   <<: *base  # base anchor will be merged
  #   age: 20

  # foo name won't be changed and it will be: John. On the other hand, bar's
  # name will be changed to the base one: Everyone has same name

  # В YAML есть теги (tags), которые используются для явного объявления типов.
  # Syntax: !![typeName] [value]
  explicit_boolean: !!bool true
  explicit_integer: !!int 42
  explicit_float: !!float -42.24
  explicit_string: !!str 0.5
  # Unexpected tag 'tag:yaml.org,2002:timestamp'
  # explicit_datetime: !!timestamp 2022-11-17 12:34:56.78 +9
  explicit_null: !!null null

  # could not determine a constructor for the tag
  # 'tag:yaml.org,2002:python/complex' in
  # ".github/workflows/workflows_lessons.yml", line 216, column 26
  # # В некоторых парсерах реализованы теги для конкретного языка, пример для
  # # Python пример сложного числового типа.
  # python_complex_number: !!python/complex 1+2j

  # could not determine a constructor for the tag
  # 'tag:yaml.org,2002:python/tuple' in
  # ".github/workflows/workflows_lessons.yml", line 223, column 5
  # # Мы можем использовать сложные ключи с включенными в них тегами из
  # # определенного языка
  # ? !!python/tuple [ 5, 7 ]
  # : Fifty Seven
  # # Могло бы быть {(5, 7): 'Fifty Seven'} в Python

  #######################
  # Дополнительные типы #
  #######################

  # Строки и числа не единственные величины которые может понять YAML.
  # YAML также поддерживает даты и время в формате ISO.
  datetime_canonical: 2001-12-15T02:59:43.1Z
  datetime_space_separated_with_time_zone: 2001-12-14 21:59:43.10 -5
  date_implicit: 2002-12-14
  # Unexpected tag 'tag:yaml.org,2002:timestamp'
  # date_explicit: !!timestamp 2002-12-14

  # The scalar style 'Literal' on line 244 and column 13 is not valid with the
  # tag 'tag:yaml.org,2002:binary'
  # # Тег !!binary показывает что эта строка является base64-закодированным
  # # представлением двоичного объекта.
  # gif_file: !!binary |
  #   R0lGODlhDAAMAIQAAP//9/X17unp5WZmZgAAAOfn515eXvPz7Y6OjuDg4J+fn5
  #   OTk6enp56enmlpaWNjY6Ojo4SEhP/++f/++f/++f/++f/++f/++f/++f/++f/+
  #   +f/++f/++f/++f/++f/++SH+Dk1hZGUgd2l0aCBHSU1QACwAAAAADAAMAAAFLC
  #   AgjoEwnuNAFOhpEMTRiggcz4BNJHrv/zCFcLiwMWYNG84BwwEeECcgggoBADs=

  # (Line: 254, Col: 5): A mapping was not expected
  # # YAML может использовать объекты типа ассоциативных массивов (set), как
  # # представлено ниже:
  # set:
  #   ? item1
  #   ? item2
  #   ? item3
  # (Line: 257, Col: 7): A mapping was not expected
  # or: {item1, item2, item3}

  # (Line: 261, Col: 5): A mapping was not expected
  # # Сеты (set) являются простыми эквивалентами словарей со значениями
  # # типа null; запись выше эквивалентна следующей:
  # # Sets are just maps with null values; the above is equivalent to:
  # set2:
  #   item1: null
  #   item2: null
  #   item3: null

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: ${{ fromJSON(vars.MATRIX_OSs) }}
        include:
          # TODO: понять как работает matrix.os
          - os: macos-latest
            platform: "darwin"
          - os: ubuntu-latest
            platform: "linux"
          - os: windows-latest
            platform: "win32"

    env:
      env-0-grep-E: |
        echo "env-0-grep-E:"
        env -0 | grep -E -z "^(another_key|a_number_value)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(scientific_notation)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(hex_notation|octal_notation)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(boolean|null_value)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(another_null_value)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(key with spaces)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(no|yes|not_enclosed|enclosed)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(however)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(Ключ заключенный в кавычки[.])=" | tr "\0" "\n"
        env -0 | grep -E -z "^(single quotes|double quotes)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(Superscript two.*)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(special_characters)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(literal_block|folded_style)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(literal_strip|block_strip)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(literal_keep|block_keep)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(0\.25)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(anchored_content|other_anchor)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(explicit_boolean)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(explicit_integer|explicit_float)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(explicit_string)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(explicit_null)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(datetime_canonical)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(datetime_space_separated_.*)=" | tr "\0" "\n"
        env -0 | grep -E -z "^(date_implicit)=" | tr "\0" "\n"
        echo "---"

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        if: ${{ matrix.platform != 'win32' }}
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          # python -m yamllint .

      - name: Check booleans
        shell: bash
        run: |
          echo "env.no is ${{ case(!env.no, 'false', 'true') }}"
          # echo "fromJSON(env.no)=$#{{ fromJSON(env.no) }}"
          echo "env.yes is ${{ case(!env.yes, 'false', 'true') }}"
          # echo "fromJSON(env.yes)=$#{{ fromJSON(env.yes) }}"
          echo "env.not_enclosed is" \
               "${{ case(!env.not_enclosed, 'false', 'true') }}"
          # echo "fromJSON(env.not_enclosed)=$#{{ fromJSON(env.not_enclosed) }}"
          echo "env.enclosed is" \
               "${{ case(env.enclosed == 'yes', 'yes', 'NOT YES') }}"

      - shell: bash
        run: |
          echo "key=$key"
          ${{ env.env-0-grep-E }}
          echo "Ключ заключенный в кавычки.=$(
                  env | sed -n '/^Ключ заключенный в кавычки\.=/s///p')"
          echo "single quotes=$(env | sed -n '/^single quotes=/s///p')"
          echo "double quotes=$(env | sed -n '/^double quotes=/s///p')"
          echo "literal_block=$literal_block"

      - shell: pwsh
        run: |
          "key=$env:key"
          ${{ env.env-0-grep-E }}
          "Ключ заключенный в кавычки.=${env:Ключ заключенный в кавычки.}"
          "single quotes=${env:single quotes}"
          "double quotes=${env:double quotes}"
          "literal_block=$env:literal_block"

      - if: ${{ matrix.platform == 'win32' }}
        shell: cmd
        run: |
          echo "key=%key%"
          ${{ env.env-0-grep-E }}
          echo "Ключ заключенный в кавычки.=%Ключ заключенный в кавычки.%"
          echo "single quotes=%single quotes%"
          echo "double quotes=%double quotes%"
          echo "literal_block=%literal_block%"

      - name: Test action Learn GitHub
        uses: ./
        with:
          # cache: false
          verbose: true

      - name: Test Learn GitHub
        env: &base
          name: Каждый будет иметь одинаковое имя
        run: |
          learn_github

      - name: Test Learn GitHub
        env: *base
          age: 10
        if: runner.os != 'Windows'
        shell: bash
        run: |
          learn_github

      - name: Test Learn GitHub
        env:  # &bar
          # <<: *base
          age: 20
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "PATH=%PATH%"
          echo "---"
          echo "LEARN_GITHUB=%LEARN_GITHUB%"
          learn_github
