---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2025 Сергей Леонтьев (leo@sai.msu.ru)

name: Workflows Lessons by Learn YAML in Y minutes

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  key: value
  another_key: Another value goes here.
  a_number_value: 100
  scientific_notation: 1e+12
  hex_notation: 0x123   # evaluates to 291
  octal_notation: 0123  # evaluates to 83

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: "darwin"
          - os: ubuntu-latest
            platform: "linux"
          - os: windows-latest
            platform: "win32"

    env:
      boolean: true
      null_value: null
      another_null_value: ~
      key with spaces: value

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          python -m yamllint .

      - shell: bash
        run: |
          echo "key=$key"
          printenv | grep -E "another_key|a_number_value|scientific_notation"
          printenv | grep -E "hex_notation|octal_notation"
          printenv | grep -E "boolean|null_value|another_null_value|spaces"

      - shell: pwsh
        run: |
          "key=$env:key"
          printenv | grep -E "another_key|a_number_value|scientific_notation"
          printenv | grep -E "hex_notation|octal_notation"
          printenv | grep -E "boolean|null_value|another_null_value|spaces"

      - if: ${{ matrix.platform == 'win32' }}
        shell: cmd
        run: |
          echo "key=%key%"
          printenv | grep -E "another_key|a_number_value|scientific_notation"
          printenv | grep -E "hex_notation|octal_notation"
          printenv | grep -E "boolean|null_value|another_null_value|spaces"
